name: "Release nightly snapshots"
on:
  push:
    branches:
      - develop

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish snapshot
      run: ./gradlew publish
      env:
        USERNAME: msfjarvis
        PASSWORD: ${{ secrets.PACKAGES_TOKEN }}
        SNAPSHOT: true
