name: "Publish releases to GitHub Packages"
on:
  release:
    types: [created]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish snapshot
      run: ./gradlew publish
      env:
        USERNAME: msfjarvis
        PASSWORD: ${{ secrets.PACKAGES_TOKEN }}
